import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { mockOrders } from "./AdminDashboard";
import { ArrowLeft } from "lucide-react";

export default function OrderDetail() {
  const { orderId } = useParams();
  const navigate = useNavigate();
  const order = (mockOrders || []).find(o => o.id === orderId) || {};
  const { images = [], customer = "", date = "", amount = 0, status = "", id = "", } = order;

  return (
    <div className="min-h-screen w-full flex flex-col bg-gradient-to-br from-gray-50 to-green-50 items-center justify-center py-10 px-2">
      {/* Subtle back button above card */}
      <div className="w-full max-w-3xl flex items-start mb-2">
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-gray-500 hover:text-green-700 font-semibold text-base px-4 py-2 rounded-lg bg-white shadow border border-gray-200 transition-all"
        >
          <ArrowLeft size={20} />
          Back to Orders
        </button>
      </div>
      <div className="w-full max-w-3xl flex flex-col items-center justify-center min-h-[60vh]">
        <div className="bg-white rounded-2xl shadow-xl p-8 border border-gray-100 flex flex-col md:flex-row gap-8 w-full">
          {/* Left: Images Preview Column */}
          <div className="flex-1 min-w-0 flex flex-col mb-6 md:mb-0">
            <h3 className="font-semibold text-lg mb-4 text-green-800">Ordered Photos</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {images.length === 0 && <div className="text-gray-400">No images</div>}
              {images.map((img: string, idx: number) => (
                <div key={idx} className="bg-gray-50 rounded-xl border shadow flex flex-col items-center justify-center p-2">
                  <div className="w-full aspect-[3/2] bg-white rounded-lg overflow-hidden flex items-center justify-center">
                    <img src={img} alt={`Order Photo ${idx + 1}`} className="object-cover w-full h-full" />
                  </div>
                  <div className="text-xs text-gray-600 mt-2">Photo {idx + 1}</div>
                </div>
              ))}
            </div>
          </div>
          {/* Right: Invoice Details */}
          <div className="w-full md:w-96 flex flex-col justify-center">
            <div className="bg-white rounded-xl shadow-lg border border-gray-100 p-6 flex flex-col gap-4">
              <h3 className="font-semibold text-lg mb-2 text-green-900">Order Invoice</h3>
              <div className="flex justify-between text-sm text-gray-700"><span>Order ID:</span><span>{id}</span></div>
              <div className="flex justify-between text-sm text-gray-700"><span>Date:</span><span>{date}</span></div>
              <div className="flex justify-between text-sm text-gray-700"><span>Customer:</span><span>{customer}</span></div>
              <div className="flex justify-between text-sm text-gray-700"><span>Status:</span><span>{status}</span></div>
              <div className="flex justify-between text-sm text-gray-700"><span>Photo Count:</span><span>{images.length}</span></div>
              <div className="border-t my-2"></div>
              <div className="flex justify-between font-bold text-2xl text-green-900"><span>Total</span><span>${amount.toFixed(2)}</span></div>
              <Button className="w-full bg-gradient-to-r from-green-500 to-emerald-500 text-white font-semibold shadow hover:scale-105 transition-all">Print Invoice</Button>
              <div className="text-xs text-gray-400 text-center mt-1">Invoice generated by M2 Photography</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 